/**
 * axon run-local <template> — run a deployment script locally for testing.
 *
 * Uses `tsx` (preferred) or `ts-node` to execute the TypeScript entry file
 * with a mock _STD_ global injected.
 */

import { execFile } from 'node:child_process';
import { join, resolve, normalize } from 'node:path';
import { access } from 'node:fs/promises';
import { createRequire } from 'node:module';
import { loadConfig, generateRuntimeBootstrap } from '@axonsdk/sdk';
import { config as loadDotenv } from '../utils/env.js';

async function getChalk() {
  const mod = await import('chalk');
  return mod.default;
}

async function getOra() {
  const mod = await import('ora');
  return mod.default;
}

// ─── Runtime shim ─────────────────────────────────────────────────────────────
// The mock runtime is generated by the SDK's runtime module, which sets up both
// `globalThis.axon` and `globalThis._STD_` (backward compat).

// ─── Runner logic ─────────────────────────────────────────────────────────────

/** Resolve path to tsx or ts-node binary */
async function resolveRunner(): Promise<{ bin: string; args: string[] }> {
  const requireFromHere = createRequire(import.meta.url);

  // Try tsx first (faster, no config needed)
  try {
    const tsxPkg = requireFromHere.resolve('tsx/package.json');
    const tsxDir = tsxPkg.replace('/package.json', '');
    return { bin: join(tsxDir, 'dist', 'cli.js'), args: [] };
  } catch {
    // tsx not found
  }

  // Try ts-node
  try {
    const tsNodePkg = requireFromHere.resolve('ts-node/package.json');
    const tsNodeDir = tsNodePkg.replace('/package.json', '');
    return { bin: join(tsNodeDir, 'dist', 'bin.js'), args: ['--esm'] };
  } catch {
    // ts-node not found
  }

  // Last resort: npx tsx
  return { bin: 'npx', args: ['tsx'] };
}

export async function runLocal(
  templateOrPath: string | undefined,
  cwd: string = process.cwd()
): Promise<void> {
  const chalk = await getChalk();
  const ora = await getOra();

  loadDotenv(cwd);

  let entryFile: string;

  if (templateOrPath) {
    // Check if it's a built-in template name
    const builtinTemplates = ['inference', 'oracle', 'blank'];
    if (builtinTemplates.includes(templateOrPath)) {
      // Resolve from templates directory
      const thisDir = new URL(import.meta.url).pathname;
      const templatesDir = resolve(
        thisDir,
        '..', '..', '..', '..', '..', 'templates', templateOrPath
      );
      entryFile = join(templatesDir, 'src', 'index.ts');
    } else {
      // Treat as a path — verify it stays within the project directory
      entryFile = resolve(cwd, templateOrPath);
      const normalizedCwd = normalize(cwd) + (cwd.endsWith('/') ? '' : '/');
      if (!normalize(entryFile).startsWith(normalizedCwd)) {
        console.error(
          chalk.red(
            `  Error: Path "${templateOrPath}" escapes the project directory. ` +
              `Only paths within the project are allowed.`
          )
        );
        process.exit(1);
      }
    }
  } else {
    // Load from axon.json
    try {
      const config = await loadConfig(cwd);
      entryFile = resolve(cwd, config.entryFile);
    } catch (err) {
      console.error(chalk.red(`  Error: ${(err as Error).message}`));
      process.exit(1);
    }
  }

  // Verify the file exists
  try {
    await access(entryFile);
  } catch {
    console.error(chalk.red(`  Error: Entry file not found: ${entryFile}`));
    console.error(
      chalk.gray(
        '  Usage: axon run-local [inference|oracle|blank|path/to/script.ts]'
      )
    );
    process.exit(1);
  }

  const spinner = ora('Starting local runner...').start();
  let runner: { bin: string; args: string[] };
  try {
    runner = await resolveRunner();
  } catch (err) {
    spinner.fail(`Failed to find TypeScript runner: ${(err as Error).message}`);
    console.log(
      chalk.yellow(
        '\n  Install tsx to run TypeScript files locally:\n' +
          chalk.white('  npm install -g tsx')
      )
    );
    process.exit(1);
  }

  spinner.stop();

  console.log();
  console.log(chalk.bold(`  Running ${chalk.cyan(entryFile)} locally...`));
  console.log(chalk.gray('  (using mock axon runtime — behaviour may differ from TEE)\n'));

  // Inject the mock runtime via NODE_OPTIONS --import
  const shimContent = generateRuntimeBootstrap('mock');

  // Write shim to a temp file
  const { mkdtemp, writeFile: writeFileFs, rm } = await import('node:fs/promises');
  const { tmpdir } = await import('node:os');
  const tmpDir = await mkdtemp(join(tmpdir(), 'axon-run-'));
  const shimPath = join(tmpDir, '_std_shim.mjs');
  await writeFileFs(shimPath, shimContent, 'utf8');

  try {
    const child = execFile(
      process.execPath, // node
      [
        '--import', shimPath,
        ...runner.args,
        ...(runner.bin !== process.execPath ? [runner.bin] : []),
        entryFile,
      ],
      {
        cwd,
        env: {
          ...process.env,
          AXON_RUN_LOCAL: '1',
        },
        timeout: 30_000,
      }
    );

    child.stdout?.pipe(process.stdout);
    child.stderr?.pipe(process.stderr);

    child.on('exit', (code) => {
      rm(tmpDir, { recursive: true, force: true }).catch(() => {});
      if (code === 0) {
        console.log();
        console.log(chalk.green('  Local run completed.'));
      } else {
        console.log();
        console.log(chalk.red(`  Local run exited with code ${code}.`));
      }
    });

    child.on('error', (err) => {
      rm(tmpDir, { recursive: true, force: true }).catch(() => {});
      // If node couldn't run the file, fall back to tsx directly
      console.error(chalk.red(`\n  Runner error: ${err.message}`));
      console.log(
        chalk.yellow(
          '\n  Try running manually:\n' +
            chalk.white(`  npx tsx ${entryFile}`)
        )
      );
      process.exit(1);
    });
  } catch (err) {
    await rm(tmpDir, { recursive: true, force: true }).catch(() => {});
    throw err;
  }
}
